#█████████                                     ████
#███░░░░░███                                   ░░███
#░███    ░░░   ██████   ██████   █████████████   ░███   ██████   █████   █████
#░░█████████  ███░░███ ░░░░░███ ░░███░░███░░███  ░███  ███░░███ ███░░   ███░░
#░░░░░░░░███░███████   ███████  ░███ ░███ ░███  ░███ ░███████ ░░█████ ░░█████
#███    ░███░███░░░   ███░░███  ░███ ░███ ░███  ░███ ░███░░░   ░░░░███ ░░░░███
#░░█████████ ░░██████ ░░████████ █████░███ █████ █████░░██████  ██████  ██████
#░░░░░░░░░   ░░░░░░   ░░░░░░░░ ░░░░░ ░░░ ░░░░░ ░░░░░  ░░░░░░  ░░░░░░  ░░░░░░

#██████████                       ████
#░░███░░░░███                     ░░███
#░███   ░░███ █████ ████  ██████  ░███   █████
#░███    ░███░░███ ░███  ███░░███ ░███  ███░░
#░███    ░███ ░███ ░███ ░███████  ░███ ░░█████
#░███    ███  ░███ ░███ ░███░░░   ░███  ░░░░███
#██████████   ░░████████░░██████  █████ ██████
#░░░░░░░░░░     ░░░░░░░░  ░░░░░░  ░░░░░ ░░░░░░

#██████████                                                     ███                                      ████████
#░░███░░░░░█                                                    ░░░                                      ███░░░░███
#░███  █ ░  █████ █████ ████████   ██████   ████████    █████  ████   ██████  ████████      █████ █████░░░    ░███
#░██████   ░░███ ░░███ ░░███░░███ ░░░░░███ ░░███░░███  ███░░  ░░███  ███░░███░░███░░███    ░░███ ░░███    ███████
#░███░░█    ░░░█████░   ░███ ░███  ███████  ░███ ░███ ░░█████  ░███ ░███ ░███ ░███ ░███     ░███  ░███   ███░░░░
#░███ ░   █  ███░░░███  ░███ ░███ ███░░███  ░███ ░███  ░░░░███ ░███ ░███ ░███ ░███ ░███     ░░███ ███   ███      █
#██████████ █████ █████ ░███████ ░░████████ ████ █████ ██████  █████░░██████  ████ █████     ░░█████   ░██████████
#░░░░░░░░░░ ░░░░░ ░░░░░  ░███░░░   ░░░░░░░░ ░░░░ ░░░░░ ░░░░░░  ░░░░░  ░░░░░░  ░░░░ ░░░░░       ░░░░░    ░░░░░░░░░░
#By DroppingAnvil
DuelTop:
  # Allowed placeholders: %name% %uuid% and %elo%
  # PlaceholderAPI placeholders are processed
  format: '&b&l%name% &8&l| &r&b%elo%'
Rankings:
  Ranks:
    Silver:
      start: 500
      end: 1000
      # TODO Look into minimizing
      format: '&7Silver'
  # Create a rank structure
